import { SelectedTagProps } from "../components/tags/types";

// sugestie do autocomplete
export const tagSuggestions: SelectedTagProps[] = [
  { id: "1", name: "SEO", power: 95 },
  { id: "2", name: "Marketing", power: 92 },
  { id: "3", name: "E-commerce", power: 88 },
  { id: "4", name: "WordPress", power: 85 },
  { id: "5", name: "Social Media", power: 83 },
  { id: "6", name: "Content Marketing", power: 80 },
  { id: "7", name: "Pozycjonowanie", power: 78 },
  { id: "8", name: "SEM", power: 75 },
  { id: "9", name: "Analiza Rynku", power: 72 },
  { id: "10", name: "Reklama", power: 70 },
  { id: "11", name: "Blog", power: 68 },
  { id: "12", name: "UX", power: 65 },
  { id: "13", name: "Branding", power: 62 },
  { id: "14", name: "Email Marketing", power: 60 },
  { id: "15", name: "Strategia", power: 58 },
  { id: "16", name: "Google Ads", power: 56 },
  { id: "17", name: "Link Building", power: 54 },
  { id: "18", name: "Remarketing", power: 52 },
  { id: "19", name: "Content", power: 50 },
  { id: "20", name: "Backlink", power: 48 },
  { id: "21", name: "Influencer Marketing", power: 47 },
  { id: "22", name: "SEO On-page", power: 46 },
  { id: "23", name: "SEO Off-page", power: 45 },
  { id: "24", name: "Audyt SEO", power: 44 },
  { id: "25", name: "Optymalizacja", power: 43 },
  { id: "26", name: "PPC", power: 42 },
  { id: "27", name: "CTR", power: 41 },
  { id: "28", name: "Konwersja", power: 40 },
  { id: "29", name: "Analityka", power: 39 },
  { id: "30", name: "Mobile Marketing", power: 38 },
  { id: "31", name: "Keywords", power: 37 },
  { id: "32", name: "Landing Page", power: 36 },
  { id: "33", name: "Web Design", power: 35 },
  { id: "34", name: "CRM", power: 34 },
  { id: "35", name: "Content Strategy", power: 33 },
  { id: "36", name: "Kampanie", power: 32 },
  { id: "37", name: "Optymalizacja Konwersji", power: 31 },
  { id: "38", name: "Lejek Sprzedażowy", power: 30 },
  { id: "39", name: "Marketing Automation", power: 29 },
  { id: "40", name: "User Experience", power: 28 },
  { id: "41", name: "Słowa Kluczowe", power: 27 },
  { id: "42", name: "Raportowanie", power: 26 },
  { id: "43", name: "Zasięg", power: 25 },
  { id: "44", name: "Kampania Reklamowa", power: 24 },
  { id: "45", name: "Lead Generation", power: 23 },
  { id: "46", name: "Persona", power: 22 },
  { id: "47", name: "SEO Techniczne", power: 21 },
  { id: "48", name: "Meta Tag", power: 20 },
  { id: "49", name: "SEO Lokalne", power: 19 },
  { id: "50", name: "Optymalizacja Mobilna", power: 18 },
];
